# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 400)
        MainWindow.setMinimumSize(QtCore.QSize(480, 400))
        MainWindow.setMaximumSize(QtCore.QSize(480, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_tmax = QtWidgets.QLabel(self.centralwidget)
        self.label_tmax.setGeometry(QtCore.QRect(290, 10, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_tmax.setFont(font)
        self.label_tmax.setObjectName("label_tmax")
        self.label_tmin = QtWidgets.QLabel(self.centralwidget)
        self.label_tmin.setGeometry(QtCore.QRect(290, 50, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_tmin.setFont(font)
        self.label_tmin.setObjectName("label_tmin")
        self.label_tavg = QtWidgets.QLabel(self.centralwidget)
        self.label_tavg.setGeometry(QtCore.QRect(290, 90, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_tavg.setFont(font)
        self.label_tavg.setObjectName("label_tavg")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 300, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 300, 161, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(280, 160, 191, 81))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("value", 35.1)
        self.lcdNumber.setProperty("intValue", 35)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 256, 256))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_tmax.raise_()
        self.label_tmin.raise_()
        self.label_tavg.raise_()
        self.pushButton_2.raise_()
        self.lcdNumber.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_tmax.setText(_translate("MainWindow", "Tmax = 45°C"))
        self.label_tmin.setText(_translate("MainWindow", "Tmin = 45°C"))
        self.label_tavg.setText(_translate("MainWindow", "Tavg = 35°C"))
        self.pushButton.setText(_translate("MainWindow", "Calibration 25°C"))
        self.pushButton_2.setText(_translate("MainWindow", "Calibration 45°C"))
        self.label.setText(_translate("MainWindow", "Thermal image"))
